### ISSUE TITLE
 "country/region" key error when trying online update

### ISSUE THREAD

**Issue by ricbencar** [schrummy14/infectionFitting#1]
Very interesting software, can you improve it a bit more? The version that reads the CSV file doesn't get online updates, and the version in the subdirectory stoped working, some "country/region" key error. Could you please provide a revised version, which downloads daily data and then runs the fitting routine? Thanks for your work and efforts.

**Comment by schrummy14** [comment]
Hello,
The key issue has been fixed.
A few days ago the the way data was being reported changed and with that new column names...
